#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "xbackbone"
name = "XBackBone"
description.en = "Lightweight file manager with full ShareX support"
description.fr = "Gestionnaire de fichiers léger avec prise en charge de ShareX"

version = "3.8.1~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://xbackbone.app/"
code = "https://github.com/SergiX44/XBackBone"
fund = "https://xbackbone.app/sponsor.html"

[integration]
yunohost = ">= 11.2.30"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/xbackbone"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/sergix44/XBackBone/releases/download/3.8.1/release-v3.8.1.zip"
    sha256 = "aa605479c51f52060fd08afae9a2d02fc7e761bf216ddbe5ef879692cf2afb8a"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "release-v.*.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-intl, php8.2-mysql, php8.2-gd, php8.2-fileinfo, php8.2-zip, php8.2-ldap"

    [resources.database]
    type = "mysql"
