packaging_format = 2

id = "xbackbone"
name = "XBackBone"
description.en = "Lightweight file manager with full ShareX support"
description.fr = "Gestionnaire de fichiers léger avec prise en charge de ShareX"

version = "3.6.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
admindoc = "https://xbackbone.app/"
code = "https://github.com/SergiX44/XBackBone"
fund = "https://xbackbone.app/sponsor.html"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/xbackbone"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/SergiX44/XBackBone/releases/download/3.6.3/release-v3.6.3.zip"
        sha256 = "ac1b09a2c262714646d1593b131bcc6a88b836204b0ee02b8879b0e2c386678f"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-intl, php8.2-mysql, php8.2-gd, php8.2-fileinfo, php8.2-zip, php8.2-ldap"

    [resources.database]
    type = "mysql"
