#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#
# MODIFY URL IN APP CONFIG
#
ynh_script_progression --message="Updating app configuration..." --weight=1

# this might be a roundabout way of doing it?
if [ "$new_path" == "/" ] && [ "$old_path" == "/" ]; then
  sed -i 's|$old_domain|$new_domain' $install_dir/config.php
elif [ "$new_path" == "/" ] && [ "$old_path" != "/" ]; then
  sed -i 's|$old_domain$old_path|$new_domain'
elif [ "$new_path" != "/" ] && [ "$old_path" == "/" ]; then
  sed -i 's|$old_domain|$new_domain$new_path'
elif [ "$new_path" != "/" ] && [ "$old_path" != "/" ]; then
  sed -i 's|$old_domain$old_path|$new_domain$new_path' $install_dir/config.php
else
  ynh_print_warn --message="Didn't match a result for old/new paths. Attempting subdomain config."
  sed -i 's|$old_domain|$new_domain' $install_dir/config.php
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
