#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir "$install_dir/storage"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/config.php"

#=================================================
# FINAL BOOKSTACK INSTALL
#=================================================
ynh_script_progression "Install database"

pushd $install_dir
	php$php_version bin/migrate --install
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
